name: Contribution checks
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  stable:
    name: Run ruff
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: 3

      - name: Install and run pre-commit hooks
        uses: pre-commit/action@v3.0.1
